### ISSUE TITLE
Help people find preschools

### ISSUE THREAD

**Issue by techieshark** [CodeforAustralia/school-finder#18]
Only about 100 schools have preschools attached. So our results aren't very helpful in that regard most often:

![no-preschool](https://cloud.githubusercontent.com/assets/1072292/6726223/02b4f418-ce69-11e4-9f24-529e4d72e610.png)

People may be able to find preschools elsewhere using http://www.mychild.gov.au/sites/mychild from the federal government. 

Instead of just saying "No", we could suggest that users check the mychild.gov.au site for more options.

**Comment by Lilith-Palmer** [comment]
@techieshark Should the link always appear; as an optional click through, or only if the result is 'no'?

**Comment by techieshark** [comment]
@Lilith-Palmer oh, great question. I don't know, what do you think?

**Comment by Lilith-Palmer** [comment]
@techieshark I'm thinking always- even if the school has a preschool attached, there will usually be other options close by. And as there would usually be difficulty getting into a pre school, parents probably always need other options.

**Comment by Lilith-Palmer** [comment]
Hey, you left your cup up here!
