### ISSUE TITLE
finalize type, style 

### ISSUE THREAD

**Issue by techieshark** [CodeforAustralia/school-finder#30]
We can probably make some of the header type a little smaller (and set text-decoration: none on the school name unless we're linking to the school, since otherwise people might confuse it for a link).

**Comment by techieshark** [comment]
Hey cool I think @pixelhappy1 is able to help on this one.

**Comment by pixelhappy1** [comment]
Hey, please see some ideas below:

School type rollover colour: 39acc9  (First window)

School name
colour: d72d6c  /  text-decoration: none  /  font-size: 40px

Could add the school icon next to school name, on the left?

'About' text: 
colour: d72d6c  /  font-size: 25px  /  bold

2 column layout for the school details, with the information boxed on the second column, reversed out on grey. 

Grey box:
colour: 7e7d7d  / rounded corners

![school details section mock](https://cloud.githubusercontent.com/assets/11765965/7081704/fa6e1a82-df89-11e4-9282-6c3ed1365af2.jpg)

Cheers

**Comment by techieshark** [comment]
@pixelhappy1 Looks fantastic! :100: Thanks!

**Comment by Lilith-Palmer** [comment]
@pixelhappy1 this is awesome!
