### ISSUE TITLE
why is opportunity_class 'no' vs 'not applicable'?

### ISSUE THREAD

**Issue by techieshark** [CodeforAustralia/school-finder#42]
I'm looking at rows where `level_of_schooling` = 'Schools for Specific Purposes' and noticed that sometimes `opportunity_class`= 'No' and sometimes it is equal to 'Not applicable'. 

What is the difference between those two types of results?

**Comment by techieshark** [comment]
Related: #43

**Comment by Lilith-Palmer** [comment]
@techieshark no difference. I think this is just human error- some people have filled the information out using incorrect terms.

**Comment by techieshark** [comment]
OK cool. We can make it just one or the other then.

**Comment by techieshark** [comment]
From Rustum: "OC classes are not applicable in SSPs and Secondary schools. Only 'No' in primary"

**Comment by Rustuma** [comment]
Removed Not applicable and switched to No - then made it Boolean
