### ISSUE TITLE
why is `student_number` null some schools?

### ISSUE THREAD

**Issue by techieshark** [CodeforAustralia/school-finder#44]
The following returns `46`:

````
SELECT count(*) FROM dec_schools WHERE (student_number IS NULL)
````

A large number of those are in SSPs:

```
SELECT count(*) FROM dec_schools WHERE level_of_schooling IN ('Schools for Specific Purposes')  AND  (student_number IS NULL)
```

returns `13`.

**Comment by Rustuma** [comment]
These are either new Primary or Secondary schools, SSPs, or EECs.  If there's a 'Current enrolment' field, show a dash here

**Comment by techieshark** [comment]
I also learned that students are only sent to SSPs temporarily and that their enrolment is counted at their home school (aka the school they'd usually go to). They aren't counted at SSPs because you wouldn't want to double count.
