### ISSUE TITLE
make queries against oshc field easier

### ISSUE THREAD

**Issue by techieshark** [CodeforAustralia/school-finder#46]
Currently the `oshc` field is either `Not available` or the name of a provider. 

This means that to search _for_ a school with Outside of School Hours Care, we need a double-negative query, like:

````
SELECT oshc FROM dec_schools where oshc <> 'Not available' 
````

It'd be nicer if we could do something like

````
SELECT oshc FROM dec_schools where oshc IN ('Available')
````

and then have a field like `oshc_provider` which may or may not be null depending on whether or not OSHC is provided.

**Comment by techieshark** [comment]
We could also call it `oshc_available` and the values would be either `true` or `false`.

**Comment by Rustuma** [comment]
Data changed as requested in Source and CartoDb

**Comment by techieshark** [comment]
Great. I changed the code with https://github.com/CodeforAustralia/school-finder/commit/4668e05c10bef68d1ff0beec02fec601cc7a6c1f to make sure the provider name is still included.
